import '../contracts/json_values.dart';
import 'module_host.dart';
import 'legacy_converter.dart';
import 'module_package.dart';

import 'dart:convert';
import 'dart:io';

import 'collection_store.dart';

/// Called inside the host erasure transaction. Shared task records and the
/// separate pre-migration backup file are not owned by the erased module.
Future<void> eraseLegacyModuleArchives(CollectionStore store, String id) async {
  await store.db.customStatement(
    'DELETE FROM field_values WHERE field_key IN '
    '(SELECT key FROM field_definitions WHERE module_id=?)',
    [id],
  );
  for (final table in [
    'field_definitions',
    'rule_executions',
    'module_versions',
  ]) {
    await store.db.customStatement('DELETE FROM $table WHERE module_id=?', [
      id,
    ]);
  }
  await store.db.customStatement(
    'DELETE FROM module_installations WHERE id=?',
    [id],
  );
}

/// One-way copy. Original tables, source documents, credentials and counters
/// remain intact unless explicitly erased. No operations or domain events are
/// generated by migration.
Future<void> migrateLegacyData(CollectionStore store) async {
  if ((await store.sql(
    "SELECT value FROM host_meta WHERE key='legacy-data-v1'",
  )).isNotEmpty) {
    return;
  }
  final db = store.db;
  final erased = (await store.sql(
    "SELECT substr(key,15) AS module_id FROM host_meta WHERE substr(key,1,14)='erased-module:'",
  )).map((row) => row['module_id']).toSet();
  await db.transaction(() async {
    Future<void> put(
      String module,
      String collection,
      String id,
      Object? value,
    ) async {
      if (erased.contains(module)) return;
      await db.customStatement(
        'INSERT OR IGNORE INTO host_collections(module_id,space,name,definition) VALUES(?,?,?,?)',
        [
          module,
          'legacy-v1',
          collection,
          jsonEncode({
            'id': collection,
            'schema': {'type': 'object'},
          }),
        ],
      );
      await db.customStatement(
        'INSERT OR IGNORE INTO host_records(module_id,space,collection,id,value,revision) VALUES(?,?,?,?,?,1)',
        [module, 'legacy-v1', collection, id, jsonEncode(value)],
      );
    }

    for (final row in await db.select(db.projects).get()) {
      await put('app.tasks', 'projects', row.id, {
        ...row.toJson(),
        'createdAt': row.createdAt.toUtc().toIso8601String(),
        'updatedAt': row.updatedAt.toUtc().toIso8601String(),
        'archivedAt': row.archivedAt?.toUtc().toIso8601String(),
      });
    }
    for (final row in await db.select(db.tasks).get()) {
      await put('app.tasks', 'tasks', row.id, {
        ...row.toJson(),
        'createdAt': row.createdAt.toUtc().toIso8601String(),
        'updatedAt': row.updatedAt.toUtc().toIso8601String(),
        'completedAt': row.completedAt?.toUtc().toIso8601String(),
        'archivedAt': row.archivedAt?.toUtc().toIso8601String(),
        'deletedAt': row.deletedAt?.toUtc().toIso8601String(),
      });
    }
    for (final row in await db.select(db.labels).get()) {
      await put('app.tasks', 'labels', row.id, row.toJson());
    }
    for (final row in await db.select(db.taskLabels).get()) {
      final id = '${row.taskId}:${row.labelId}';
      await put('app.tasks', 'taskLabels', id, {'id': id, ...row.toJson()});
    }
    for (final row in await db.select(db.fieldDefinitions).get()) {
      await put(row.moduleId, 'fieldDefinitions', row.key, {
        'id': row.key,
        ...row.toJson(),
      });
    }
    for (final row in await db.select(db.fieldValues).get()) {
      final id = '${row.taskId}:${row.fieldKey}';
      final module = row.fieldKey.split(':').first;
      await put(module, 'fieldValues', id, {
        'id': id,
        'entity': {
          'moduleId': 'app.tasks',
          'collection': 'tasks',
          'id': row.taskId,
        },
        'fieldKey': row.fieldKey,
        'value': jsonDecode(row.valueJson),
        'updatedAt': row.updatedAt.toUtc().toIso8601String(),
      });
    }
    for (final row in await db.select(db.ruleExecutions).get()) {
      await put(row.moduleId, 'ruleExecutions', '${row.id}', {
        ...row.toJson(),
        'id': '${row.id}',
        'createdAt': row.createdAt.toUtc().toIso8601String(),
      });
    }
    final settings = {
      for (final row in await db.select(db.appSettings).get())
        row.key: row.value,
    };
    await put('app.ai', 'connections', 'default', {
      'id': 'default',
      'endpoint': settings['ai.endpoint'] ?? '',
      'model': settings['ai.model'] ?? '',
      'credential': 'legacy-ai-key',
    });
    await db.customStatement('INSERT OR IGNORE INTO host_meta VALUES(?,?)', [
      'credential:legacy-ai-key',
      canonicalJson({
        'moduleId': 'app.ai',
        'endpoint': settings['ai.endpoint'] ?? '',
        'alias': 'xudian.ai.apiKey',
      }),
    ]);
    if (settings['ai.assistant.history'] != null) {
      final oldHistory = object(jsonDecode(settings['ai.assistant.history']!));
      await put('app.ai', 'history', 'conversation', {
        'id': 'conversation',
        'messages': [
          for (final raw in oldHistory['messages'] as List? ?? [])
            {'role': object(raw)['role'], 'content': object(raw)['text']},
        ],
        'legacyAudit': oldHistory['audit'],
        'interrupted': oldHistory['interrupted'],
      });
    }
    if (settings['ui.layout'] != null) {
      try {
        final layout = object(jsonDecode(settings['ui.layout']!));
        for (final profile in ['narrow', 'wide']) {
          for (final raw in object(object(layout[profile])['mounts']).values) {
            final mount = object(raw), refs = <Object?>[];
            if (mount['taskId'] is String) {
              refs.add({
                'moduleId': 'app.tasks',
                'collection': 'tasks',
                'id': mount['taskId'],
              });
            }
            if (mount['projectId'] is String) {
              refs.add({
                'moduleId': 'app.tasks',
                'collection': 'projects',
                'id': mount['projectId'],
              });
            }
            if (refs.isNotEmpty) {
              mount['values'] = {
                ...object(mount['values'] ?? {}),
                'entities': refs,
              };
            }
          }
        }
        await db.customStatement(
          "UPDATE app_settings SET value=? WHERE key='ui.layout'",
          [canonicalJson(layout)],
        );
      } catch (_) {
        /* Preserve corrupt and future layout formats for recovery. */
      }
    }
    await db.customStatement(
      "INSERT INTO host_meta VALUES('legacy-data-v1','complete')",
    );
  });
}

Future<void> migrateLegacyInstallations(ModuleHost host) async {
  final store = host.store;
  if ((await store.sql(
    "SELECT value FROM host_meta WHERE key='legacy-packages-v1'",
  )).isNotEmpty) {
    return;
  }
  final rows = await store.db.select(store.db.moduleInstallations).get();
  final pending = {for (final row in rows) row.id: row};
  while (pending.isNotEmpty) {
    var progress = false;
    for (final id in pending.keys.toList()) {
      final row = pending[id]!;
      if (await host.wasErased(id)) {
        pending.remove(id);
        progress = true;
        continue;
      }
      try {
        final source = object(jsonDecode(row.sourceJson));
        final dependencies =
            (object(source['manifest'])['dependencies'] as List? ?? [])
                .cast<String>();
        if (dependencies.any(pending.containsKey)) continue;
        final existing = await store.sql(
          'SELECT module_id FROM host_installations WHERE module_id=?',
          [id],
        );
        if (existing.isEmpty) {
          await host.install(await convertLegacyModule(source));
          if (!row.installed) {
            await host.uninstall(id, cascade: true);
          } else if (!row.enabled) {
            await host.disable(id, cascade: true);
          }
        }
        pending.remove(id);
        progress = true;
      } catch (error) {
        host.failures[id] = 'Legacy conversion: $error';
        await store.db.customStatement(
          'INSERT OR REPLACE INTO host_meta VALUES(?,?)',
          ['legacy-error:$id', '$error'],
        );
        pending.remove(id);
        progress = true;
      }
    }
    if (!progress) {
      for (final id in pending.keys) {
        host.failures[id] = 'Legacy dependency cycle';
      }
      break;
    }
  }
  // Every historical source uses the same deterministic converter as the
  // active source. Explicitly erased identities must not be restored.
  for (final row in await store.db.select(store.db.moduleVersions).get()) {
    if (await host.wasErased(row.moduleId)) continue;
    try {
      final derived = await convertLegacyModule(
        object(jsonDecode(row.sourceJson)),
      );
      final blob = File(
        '${host.directory.path}/${derived.packageDigest}.xmodule',
      );
      if (!await blob.exists()) {
        await blob.writeAsBytes(derived.bytes, flush: true);
      }
      await store.db.customStatement(
        'INSERT OR IGNORE INTO host_packages VALUES(?,?,?,?,?,?,?)',
        [
          derived.id,
          derived.version,
          derived.packageDigest,
          derived.origin,
          canonicalJson(derived.release),
          canonicalJson(derived.definition),
          row.installedAt.toUtc().toIso8601String(),
        ],
      );
      await store.db.customStatement(
        'INSERT OR IGNORE INTO host_meta VALUES(?,?)',
        [
          'legacy-source:${row.moduleId}:${row.version}',
          canonicalJson(row.toJson()),
        ],
      );
    } catch (error) {
      host.failures['${row.moduleId}@${row.version}'] =
          'Historical conversion: $error';
    }
  }
  await store.db.customStatement(
    "INSERT INTO host_meta VALUES('legacy-packages-v1','complete')",
  );
}
