#!/usr/bin/env python3
"""Deterministic local packages and immutable, explicitly selected default assets."""
import argparse
import hashlib
import io
import json
import pathlib
import re
import zipfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
ID = re.compile(r'^[a-z][a-z0-9]*(\.[a-z][a-z0-9_-]*)+$')
VERSION = re.compile(r'^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$')


def safe_source_path(name):
    parts = pathlib.PurePosixPath(name).parts
    return (not name.startswith('/') and '\\' not in name and
            all(part not in ('..', '__pycache__', 'node_modules', 'build', 'dist') and
                not part.startswith('.') for part in parts) and
            pathlib.PurePosixPath(name).suffix.lower() not in
            {'.pyc', '.log', '.apk', '.aab', '.so', '.dll', '.jks', '.keystore', '.pem', '.key'})


def identity(definition):
    manifest = definition['manifest']
    module_id, version = manifest['id'], manifest['version']
    if definition.get('formatVersion') != 3 or not ID.fullmatch(module_id) or not VERSION.fullmatch(version):
        raise ValueError('Invalid script module format, identity or version')
    return module_id, version


def package_bytes(folder):
    if folder.is_symlink() or any(path.is_symlink() for path in folder.rglob('*')):
        raise ValueError('Source packages cannot contain symlinks')
    paths = {p.relative_to(folder).as_posix(): p for p in sorted(folder.rglob('*')) if p.is_file()}
    if 'package.json' in paths:
        raise ValueError('package.json is generated by this tool')
    for name in paths:
        if not safe_source_path(name):
            raise ValueError(f'Unsafe package path: {name}')
    files = {name: path.read_bytes() for name, path in paths.items()}
    identity(json.loads(files['module.json']))
    manifest = {'packageFormat': 2, 'release': {'channel': 'local'}, 'files': [
        {'path': name, 'size': len(data), 'sha256': hashlib.sha256(data).hexdigest()}
        for name, data in sorted(files.items())]}
    files['package.json'] = json.dumps(manifest, ensure_ascii=False, separators=(',', ':'), sort_keys=True).encode()
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for name, data in sorted(files.items()):
            entry = zipfile.ZipInfo(name, (1980, 1, 1, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(entry, data)
    return buffer.getvalue()


def pack(folder, destination):
    data = package_bytes(folder)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(data)
    return hashlib.sha256(data).hexdigest()


def package_identity(data):
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        names = archive.namelist()
        if len(names) != len(set(names)) or not all(safe_source_path(name) for name in names):
            raise ValueError('Duplicate or unsafe package paths')
        package = json.loads(archive.read('package.json'))
        if package.get('packageFormat') != 2:
            raise ValueError('Unsupported package format')
        listed = set()
        for item in package['files']:
            name = item['path']
            if name in listed or name == 'package.json':
                raise ValueError('Duplicate package manifest entry')
            listed.add(name)
            payload = archive.read(name)
            if len(payload) != item['size'] or hashlib.sha256(payload).hexdigest() != item['sha256']:
                raise ValueError(f'Package payload digest mismatch: {name}')
        if listed != set(names) - {'package.json'}:
            raise ValueError('Package manifest does not list every payload')
        return identity(json.loads(archive.read('module.json')))


def bundle_updates(catalog_path, asset_dir, candidates):
    """Validate every selected candidate without writing assets or the catalog."""
    entries = json.loads(catalog_path.read_text())
    if not isinstance(entries, list):
        raise ValueError('Default catalog must be an array')
    updates, seen = [], set()
    for entry in entries:
        module_id = entry['id']
        if module_id in seen or not isinstance(entry.get('default'), bool):
            raise ValueError('Duplicate default module or invalid default flag')
        seen.add(module_id)
        version, data = candidates[module_id]
        if package_identity(data) != (module_id, version):
            raise ValueError(f'Bundled package identity mismatch: {module_id}')
        name = f'{module_id}-{version}.xmodule'
        destination = asset_dir / name
        if destination.is_symlink():
            raise ValueError('Bundled assets cannot contain symlinks')
        if destination.exists() and destination.read_bytes() != data:
            raise ValueError(f'Bundled asset is immutable: {destination}; use a new version')
        updated = dict(entry, asset=f'assets/modules/{name}', sha256=hashlib.sha256(data).hexdigest())
        updates.append((destination, data, updated))
    return updates


def bundle_archives(asset_dir, updates, archive_dir):
    """Preflight obsolete files and archive collisions before any bundle writes."""
    referenced = {destination.name for destination, _, _ in updates}
    archives = []
    if archive_dir is not None:
        parent = archive_dir
        while not parent.exists() and not parent.is_symlink() and parent != parent.parent:
            parent = parent.parent
        if parent.is_symlink() or not parent.is_dir():
            raise ValueError(f'Bundle archive directory parent must be a directory: {parent}')
    for source in sorted(asset_dir.glob('*.xmodule')):
        if source.name in referenced:
            continue
        if archive_dir is None or archive_dir.resolve() == asset_dir.resolve():
            raise ValueError('An external archive directory is required for obsolete bundled assets')
        if source.is_symlink():
            raise ValueError('Bundled assets cannot contain symlinks')
        data = source.read_bytes()
        package_identity(data)
        destination = archive_dir / source.name
        if destination.is_symlink():
            raise ValueError('Bundle archive cannot contain symlinks')
        if destination.exists() and destination.read_bytes() != data:
            raise ValueError(f'Bundle archive is immutable: {destination}')
        archives.append((source, destination, data))
    return archives


def write_bundle(catalog_path, updates, archives=()):
    for destination, data, _ in updates:
        if not destination.exists():
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(data)
    for source, destination, data in archives:
        if not destination.exists():
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(data)
        source.unlink()
    catalog_path.write_text(json.dumps([entry for _, _, entry in updates], ensure_ascii=False, indent=2) + '\n')


def validate_bundle(catalog_path, asset_dir, *, allow_unreferenced=False):
    """Check pinned identities/digests and optionally reject unused package files."""
    entries = json.loads(catalog_path.read_text())
    referenced, seen = set(), set()
    for entry in entries:
        module_id = entry['id']
        if not ID.fullmatch(module_id) or module_id in seen or not isinstance(entry.get('default'), bool):
            raise ValueError('Invalid default module identity or flag')
        seen.add(module_id)
        path = pathlib.PurePosixPath(entry['asset'])
        if path.parent.as_posix() != 'assets/modules' or not path.name.endswith('.xmodule'):
            raise ValueError(f'Unsafe bundled asset reference: {entry["asset"]}')
        asset = asset_dir / path.name
        if asset.is_symlink():
            raise ValueError('Bundled assets cannot contain symlinks')
        data = asset.read_bytes()
        if hashlib.sha256(data).hexdigest() != entry['sha256']:
            raise ValueError(f'Bundled asset digest mismatch: {path.name}')
        actual_id, version = package_identity(data)
        if actual_id != module_id or path.name != f'{module_id}-{version}.xmodule':
            raise ValueError(f'Bundled asset identity mismatch: {path.name}')
        referenced.add(path.name)
    extras = {path.name for path in asset_dir.glob('*.xmodule')} - referenced
    if extras and not allow_unreferenced:
        raise ValueError(f'Unreferenced bundled packages: {", ".join(sorted(extras))}')
    return referenced


def build_modules(modules, output, catalog_path=None, archive_dir=None):
    candidates = {}
    for folder in sorted(modules.iterdir()):
        if not (folder / 'module.json').is_file():
            continue
        module_id, version = identity(json.loads((folder / 'module.json').read_text()))
        if module_id in candidates:
            raise ValueError(f'Duplicate source module: {module_id}')
        candidates[module_id] = (version, package_bytes(folder))
    updates = bundle_updates(catalog_path, catalog_path.parent, candidates) if catalog_path else None
    archives = bundle_archives(catalog_path.parent, updates, archive_dir) if catalog_path else []
    # Preflight every source and default asset before writing even local outputs.
    results = []
    for module_id, (_, data) in candidates.items():
        destination = output / f'{module_id}.xmodule'
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
        results.append((module_id, hashlib.sha256(data).hexdigest(), destination))
    if updates is not None:
        write_bundle(catalog_path, updates, archives)
    return results


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=pathlib.Path, default=ROOT / 'dist/modules')
    parser.add_argument('--defaults', action='store_true', help='Update existing default catalog entries with immutable versioned assets')
    args = parser.parse_args()
    catalog_path = ROOT / 'client/assets/modules/catalog.json' if args.defaults else None
    for module_id, sha, destination in build_modules(
            ROOT / 'packages/modules', args.output, catalog_path, ROOT / 'dist/bundle-archive'):
        print(f'{module_id} {sha} {destination}')


if __name__ == '__main__':
    main()
