#!/usr/bin/env python3
"""Deterministic, unsigned local .xmodule packer; no native or bytecode assets."""
import argparse, hashlib, json, pathlib, zipfile
ROOT = pathlib.Path(__file__).resolve().parents[2]

def pack(folder, destination):
    files = {p.relative_to(folder).as_posix(): p.read_bytes() for p in sorted(folder.rglob('*')) if p.is_file()}
    if 'package.json' in files:
        raise ValueError('package.json is generated by this tool')
    definition = json.loads(files['module.json'])
    assert definition['formatVersion'] == 3
    for name in files:
        assert not name.startswith('/') and '..' not in name.split('/') and '\\' not in name
    manifest = {'packageFormat': 2, 'release': {'channel': 'local'}, 'files': [
        {'path': name, 'size': len(data), 'sha256': hashlib.sha256(data).hexdigest()}
        for name, data in sorted(files.items())]}
    files['package.json'] = json.dumps(manifest, ensure_ascii=False, separators=(',', ':'), sort_keys=True).encode()
    destination.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(destination, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for name, data in sorted(files.items()):
            entry = zipfile.ZipInfo(name, (1980, 1, 1, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(entry, data)
    return hashlib.sha256(destination.read_bytes()).hexdigest()

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=pathlib.Path, default=ROOT / 'dist/modules')
    parser.add_argument('--defaults', action='store_true', help='Copy only the default packages and pinned catalog into client assets')
    args = parser.parse_args()
    catalog = []
    for folder in sorted((ROOT / 'packages/modules').iterdir()):
        if not (folder / 'module.json').is_file(): continue
        definition = json.loads((folder/'module.json').read_text())
        module_id = definition['manifest']['id']
        destination = args.output / (module_id + '.xmodule')
        sha = pack(folder, destination)
        print(f'{module_id} {sha} {destination}')
        if args.defaults and module_id != 'app.schedule':
            asset = ROOT / 'client/assets/modules' / destination.name
            asset.parent.mkdir(parents=True, exist_ok=True)
            asset.write_bytes(destination.read_bytes())
            catalog.append({'id': module_id, 'asset': 'assets/modules/' + destination.name, 'sha256': sha,
                            'default': definition['manifest'].get('defaultInstall', False)})
    if args.defaults:
        (ROOT/'client/assets/modules/catalog.json').write_text(json.dumps(catalog, ensure_ascii=False, indent=2)+'\n')

if __name__ == '__main__': main()
